# Generated by Django 4.1.7 on 2023-03-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet_pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='count',
            field=models.PositiveIntegerField(verbose_name='Count'),
        ),
    ]
