# Generated by Django 4.1.7 on 2023-03-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('F', 'female'), ('M', 'male')], default=23, max_length=6, verbose_name='Gender'),
            preserve_default=False,
        ),
    ]
