# Generated by Django 4.1.7 on 2023-03-26 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='related_owner_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pets', to=settings.AUTH_USER_MODEL, verbose_name="Pet' owner"),
        ),
    ]
