# Generated by Django 4.1.7 on 2023-03-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Problem description')),
                ('status', models.CharField(choices=[('CANCELED', 'CANCELED'), ('NEW', 'NEW'), ('CONFIRMED', 'CONFIRMED')], max_length=9)),
                ('appointment_time', models.TimeField(verbose_name='Appointment time')),
                ('appointment_date', models.DateField(verbose_name='Appointment date')),
            ],
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Reception date')),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Temperature')),
                ('preliminary_diagnosis', models.CharField(max_length=254, verbose_name='Preliminary diagnosis')),
                ('appointments', models.TextField(verbose_name="Doctor's appointments")),
                ('send_to_email', models.BooleanField(verbose_name='Do you want to send PDF version to email?')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
            },
        ),
    ]
