# Generated by Django 4.1.7 on 2023-03-10 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Reception date')),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Temperature')),
                ('preliminary_diagnosis', models.CharField(max_length=254, verbose_name='Preliminary diagnosis')),
                ('appointments', models.TextField(verbose_name="Doctor's appointments")),
                ('send_to_email', models.BooleanField(verbose_name='Do you want to send PDF version to email?')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctorprofile', verbose_name='Doctor')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.petownerprofile', verbose_name='Owner')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.pet', verbose_name='Pet')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Problem description')),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('CONFIRMED', 'CONFIRMED'), ('CANCELED', 'CANCELED')], max_length=9)),
                ('appointment_time', models.TimeField(verbose_name='%h-%m-%s')),
                ('appointment_date', models.DateField(verbose_name='%Y-%d-%m')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.petownerprofile', verbose_name="Owner' name")),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.pet', verbose_name='Pet')),
            ],
        ),
    ]
