# Generated by Django 4.1.7 on 2023-03-26 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('appointment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('CANCELED', 'CANCELED'), ('FINISHED', 'FINISHED'), ('NEW', 'NEW'), ('CONFIRMED', 'CONFIRMED')], default='NEW', max_length=9),
        ),
        migrations.AlterField(
            model_name='reception',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appointment.appointment', verbose_name='Select appointment'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='related_owner_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.pet', verbose_name="Owner's full name"),
        ),
    ]
