# Generated by Django 4.1.7 on 2023-03-26 00:16

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_owner_appointment_pet_reception_doctor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reception',
            old_name='recommended_research',
            new_name='recommended_researches',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 3, 26))], verbose_name='Appointment date'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'CONFIRMED'), ('FINISHED', 'FINISHED'), ('NEW', 'NEW'), ('CANCELED', 'CANCELED')], default='NEW', max_length=9),
        ),
        migrations.AlterField(
            model_name='reception',
            name='gender',
            field=models.CharField(choices=[('F', 'female'), ('M', 'male')], max_length=6, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name="Pet's weight(kg)"),
        ),
    ]
