# Generated by Django 4.1.7 on 2023-03-24 22:37

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date.today)], verbose_name='Appointment date'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('FINISHED', 'FINISHED'), ('CONFIRMED', 'CONFIRMED'), ('CANCELED', 'CANCELED')], max_length=9),
        ),
    ]
