# Generated by Django 4.1.7 on 2023-03-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_status_alter_reception_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('CANCELED', 'CANCELED'), ('NEW', 'NEW'), ('FINISHED', 'FINISHED'), ('CONFIRMED', 'CONFIRMED')], default='NEW', max_length=9),
        ),
    ]
