# Generated by Django 4.1.7 on 2023-03-25 11:36

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 3, 25))], verbose_name='Appointment date'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('FINISHED', 'FINISHED'), ('CONFIRMED', 'CONFIRMED'), ('NEW', 'NEW'), ('CANCELED', 'CANCELED')], default='NEW', max_length=9),
        ),
        migrations.AlterField(
            model_name='reception',
            name='temperature',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Temperature'),
        ),
    ]
