# Generated by Django 4.1.7 on 2023-03-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_remove_reception_gender_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='gender',
            field=models.CharField(default=23, max_length=6, verbose_name='Gender'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('CONFIRMED', 'CONFIRMED'), ('FINISHED', 'FINISHED'), ('CANCELED', 'CANCELED')], default='NEW', max_length=9),
        ),
    ]
