# Generated by Django 4.1.7 on 2023-04-02 12:26

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 4, 2))], verbose_name='Appointment date'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('CANCELED', 'CANCELED'), ('CONFIRMED', 'CONFIRMED'), ('FINISHED', 'FINISHED'), ('NEW', 'NEW')], default='NEW', max_length=9),
        ),
        migrations.AlterField(
            model_name='reception',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Price'),
        ),
    ]
